swagger: '2.0'
basePath: /api/v1
host: localhost:3001
info:
  description: Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  title: Bank Argent API documentation
  version: 1.0.0
schemes:
  - http
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
paths:
  /user/login:
    post:
      description: API for Login
      parameters:
        - description: Login Payload
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      summary: Login
      tags:
        - User Module
  /user/profile:
    get:
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
      summary: User Profile API
      tags:
        - User Module
    put:
      description: API for updating a user profile
      parameters:
        - description: Update user profile attributes
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
      summary: User Profile API
      tags:
        - User Module
  /user/signup:
    post:
      description: API for Signup
      parameters:
        - description: Signup Payload
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      summary: Signup
      tags:
        - User Module
  /user/{userID}/transactions:
    get:
      description: Retrieve all transactions for the logged-in user, grouped by account, for the current month.
      parameters:
        - description: ID of the account to filter transactions by specific account.
          in: query
          name: accountId
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response with list of transactions grouped by account
          schema:
            items:
              $ref: '#/definitions/Transaction'
            type: array
        '401':
          description: Unauthorized access
        '404':
          description: No transactions found for the current month
      summary: Get transactions for the current month
      tags:
        - Transactions Module
  /user/{userID}/transactions/{transactionID}:
    get:
      description: Retrieve detailed information for a specific transaction.
      parameters:
        - description: Unique identifier of the transaction to retrieve details for.
          in: path
          name: transactionID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response with transaction details
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized access
        '404':
          description: Transaction not found
      summary: Get transaction details
      tags:
        - Transactions Module
    put:
      description: Modify specific details of a transaction (e.g., category or notes).
      parameters:
        - description: Unique identifier of the transaction to update.
          in: path
          name: transactionID
          required: true
          type: string
        - in: body
          name: body
          description: Transaction details to update
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction successfully updated
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Bad request, invalid data provided
        '401':
          description: Unauthorized access
        '404':
          description: Transaction not found
      summary: Update transaction information
      tags:
        - Transactions Module
definitions:
  ApiResponse:
    properties:
      body:
        properties:
          email:
            type: string
          id:
            type: string
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
  Login:
    properties:
      email:
        description: user email
        type: string
      password:
        description: user password
        type: string
  LoginResponse:
    properties:
      token:
        type: string
    type: object
  Transaction:
    properties:
      accountId:
        description: Unique identifier of the account associated with the transaction
        type: string
      amount:
        description: Amount of the transaction
        format: float
        type: number
      category:
        description: Category assigned to the transaction
        type: string
      date:
        description: Date and time of the transaction
        format: date-time
        type: string
      description:
        description: Brief description or label of the transaction
        type: string
      id:
        description: Unique identifier of the transaction
        type: string
      notes:
        description: Optional notes about the transaction
        type: string
    type: object
  TransactionUpdate:
    properties:
      category:
        description: New category for the transaction
        type: string
      notes:
        description: Updated notes for the transaction
        type: string
    type: object
  User:
    properties:
      email:
        description: user email
        type: string
      firstName:
        description: user first name
        type: string
      lastName:
        description: user last name
        type: string
      password:
        description: user password
        type: string
      userName:
        description: user public name
        type: string
  UserProfile:
    properties:
      userName:
        type: string
    type: object
